In [1]:
# Importar librerias.
import pandas as pd
import numpy as np

In [2]:
# Carga de los datasets por plataforma.
df_amazon=pd.read_csv('Datasets/amazon_prime_titles.csv')
df_disney=pd.read_csv('Datasets/disney_plus_titles.csv')
df_hulu=pd.read_csv('Datasets/hulu_titles.csv')
df_netflix=pd.read_csv('Datasets/netflix_titles.csv')

In [3]:
# Carga de los datasets ocn los puntajes.
df_ratings1=pd.read_csv('Datasets/ratings/1.csv')
df_ratings2=pd.read_csv('Datasets/ratings/2.csv')
df_ratings3=pd.read_csv('Datasets/ratings/3.csv')
df_ratings4=pd.read_csv('Datasets/ratings/4.csv')
df_ratings5=pd.read_csv('Datasets/ratings/5.csv')
df_ratings6=pd.read_csv('Datasets/ratings/6.csv')
df_ratings7=pd.read_csv('Datasets/ratings/7.csv')
df_ratings8=pd.read_csv('Datasets/ratings/8.csv')

In [4]:
# Se agrega la inicial segun la plataforma para complementar el campo id y hacerlo unico.
df_amazon['show_id']=df_amazon['show_id'].map('a{}'.format)
df_amazon['platform']= 'amazon'
df_disney['show_id']=df_disney['show_id'].map('d{}'.format)
df_disney['platform']= 'disney'
df_hulu['show_id']=df_hulu['show_id'].map('h{}'.format)
df_hulu['platform']= 'hulu'
df_netflix['show_id']=df_netflix['show_id'].map('n{}'.format)
df_netflix['platform']= 'netflix'

In [5]:
# Union de los datasets para continuar con las transformaciones.
df_stream_platforms = pd.concat([df_amazon,df_disney,df_hulu,df_netflix], ignore_index=True)
df_ratings = pd.concat([df_ratings1,df_ratings2,df_ratings3,df_ratings4,df_ratings5,df_ratings6,df_ratings7,df_ratings8], ignore_index=True)

# Cambio del nombre de las colummnas para ajustarlo al requerimiento.
df_stream_platforms=df_stream_platforms.rename(columns={'show_id':'id'})
df_ratings=df_ratings.rename(columns={'movieId':'id'})
df_ratings=df_ratings.rename(columns={'rating':'score'})

In [6]:
# Creacion de la columna score basada en el promedio de los puntajes.
score=df_ratings.groupby(['id'],as_index=False)['score'].mean()

In [7]:
# Se agrega la columna score ajustandola a su correspondiente id.
df_stream_platforms=pd.merge(df_stream_platforms,score, how='outer',on='id')
df_stream_platforms

,id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platform,score
0,as1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,amazon,3.467131
1,as2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,amazon,3.548682
2,as3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,amazon,3.500000
3,as4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyonc√©, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",amazon,3.538055
4,as5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,amazon,3.478992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,ns8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",netflix,3.438998
22994,ns8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",netflix,3.515947
22995,ns8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,netflix,3.420945
22996,ns8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",netflix,3.588050
22997,ns8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,netflix,3.529228

In [8]:
# Se reemplazan los valores faltantes del campo rating con la clasificacion G.
df_stream_platforms['rating']=df_stream_platforms['rating'].replace([np.nan],'G')

In [9]:
# Funcion querelaiza la conversion de la fecha a un valor numerico:
def fecha_a_numero(dato):
    # Asignar un valor dummie en caso de ser un campo faltante.
    if dato == "nofecha":
        return "1991/1/1"
    else:
    # Manejo de listas para asignar cada parte de la fecha:
        lfecha=[]
        lmes=[]
    # Se recorre le dato para ir extrayendo los campos.
        for i in str(dato):
            lfecha.append(i)

        for i in lfecha:
            if i == " ":
                break
            else:
                lmes.append(i)
        mes=''.join(lmes)

        lfecha=lfecha[len(lmes):]
        la√±o= lfecha[(len(lfecha)-4):len(lfecha)]
        ldia= lfecha[(len(lfecha)-8):(len(lfecha)-4)]
    # Se filtra por mes para asignar su valor correspondiente.
        if mes == 'January':
            la√±o.append("/")
            la√±o.append("1")
            la√±o.append("/")
        elif mes == 'February':
            la√±o.append("/")
            la√±o.append("2")
            la√±o.append("/")
        elif mes == 'March':
            la√±o.append("/")
            la√±o.append("3")
            la√±o.append("/")
        elif mes == 'April':
            la√±o.append("/")
            la√±o.append("4")
            la√±o.append("/")
        elif mes == 'May':
            la√±o.append("/")
            la√±o.append("5")
            la√±o.append("/")
        elif mes == 'June':
            la√±o.append("/")
            la√±o.append("6")
            la√±o.append("/")
        elif mes == 'July':
            la√±o.append("/")
            la√±o.append("7")
            la√±o.append("/")
        elif mes == 'August':
            la√±o.append("/")
            la√±o.append("8")
            la√±o.append("/")
        elif mes == 'September':
            la√±o.append("/")
            la√±o.append("9")
            la√±o.append("/")
        elif mes == 'October':
            la√±o.append("/")
            la√±o.append("10")
            la√±o.append("/")
        elif mes == 'November':
            la√±o.append("/")
            la√±o.append("11")
            la√±o.append("/")
        else:
            la√±o.append("/")
            la√±o.append("12")
            la√±o.append("/")
       
    # Se recorre el string para determinar el dia.
        for i in ldia:
            if i == ",":
                break
            elif i == " ":
                continue
            else:
                la√±o.append(i)
        resultado=''.join(la√±o)
        return resultado

In [10]:
# Se reemplazan los valores faltantes de la fecha.
df_stream_platforms['date_added']= df_stream_platforms['date_added'].replace(np.nan,'nofecha')

In [11]:
# Se modifica el valor en string por un valor numerico.
df_stream_platforms['date_added']= df_stream_platforms['date_added'].map(lambda x:fecha_a_numero(x))

In [12]:
# Se hace el cambio de tipo de dato y se formatea segun el requerimiento.
df_stream_platforms['date_added']= pd.to_datetime(df_stream_platforms['date_added'], format='%Y/%m/%d')

In [13]:
#Se estandarizan los valores a caracteres en minuscula.
df_stream_platforms['id'] =df_stream_platforms['id'].str.lower()
df_stream_platforms['type'] =df_stream_platforms['type'].str.lower()
df_stream_platforms['director'] =df_stream_platforms['director'].str.lower()
df_stream_platforms['cast'] =df_stream_platforms['cast'].str.lower()
df_stream_platforms['country'] =df_stream_platforms['country'].str.lower()
df_stream_platforms['rating'] =df_stream_platforms['rating'].str.lower()
df_stream_platforms['duration'] =df_stream_platforms['duration'].str.lower()
df_stream_platforms['listed_in'] =df_stream_platforms['listed_in'].str.lower()
df_stream_platforms['description'] =df_stream_platforms['description'].str.lower()

In [14]:
# la funcion permite extraer el tipo de duracion en el campo duration.
def conversion_numero_duration(dato):
    if dato == 'NaN':
        return np.nan
    else:
        duration=[]
        numero=[]
        for i in str(dato):
            duration.append(i)

        for i in duration:
            if i == " ":
                break
            else:
                numero.append(i)
        resulta=''.join(numero)
    return resulta

In [15]:
# la funcion permite extraer el tiempo de duracion en el campo duration.
def conversion_tipo_duration(dato):
    if dato == 'NaN':
        return np.nan
    else:
        duration=[]
        numero=[]
        for i in str(dato):
            duration.append(i)

        for i in duration:
            if i == " ":
                break
            else:
                numero.append(i)
        tipo=duration[len(numero)+1:len(duration)]
        resulta=''.join(tipo)
    return resulta

In [16]:
# Se crean dos campos nuevos para dividir el campo duration en int y type.
df_stream_platforms['duration_int']=df_stream_platforms['duration'].map(lambda x:conversion_numero_duration(x)) 
df_stream_platforms['duration_type']=df_stream_platforms['duration'].map(lambda x:conversion_tipo_duration(x) )

In [17]:
# Se reemplazan los valores faltantes.
df_stream_platforms['duration_int']= df_stream_platforms['duration_int'].replace('nan','0')
df_stream_platforms['duration_type']= df_stream_platforms['duration_type'].replace('season','seasons')
# Se cambia el tipo del campo a entero y se cambia todo en minuscula en el campo type. 
df_stream_platforms['duration_int']= df_stream_platforms['duration_int'].astype('Int32')
df_stream_platforms['duration_type'] =df_stream_platforms['duration_type'].str.lower()

In [18]:
# Se exporta todo a un csv con los datos transformados.
df_stream_platforms.to_csv('stream_platforms.csv', index= False)

In [18]:
df=pd.read_csv('stream_platforms.csv')
df

,id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,platform,score,duration_int,duration_type
0,as1,movie,The Grand Seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,amazon,3.467131,113,min
1,as2,movie,Take Care Good Night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,amazon,3.548682,110,min
2,as3,movie,Secrets of Deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,amazon,3.500000,74,min
3,as4,movie,Pink: Staying True,sonia anderson,"interviews with: pink, adele, beyonc√©, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",amazon,3.538055,69,min
4,as5,movie,Monster Maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,amazon,3.478992,45,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,ns8803,movie,Zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",netflix,3.438998,158,min
22994,ns8804,tv show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,tv-y7,2 seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",netflix,3.515947,2,seasons
22995,ns8805,movie,Zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019-11-01,2009,r,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,netflix,3.420945,88,min
22996,ns8806,movie,Zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020-01-11,2006,pg,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",netflix,3.588050,88,min
22997,ns8807,movie,Zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,netflix,3.529228,111,min